version: '3'

services:
  song-service:
    build: ./SongService
    restart: always
    depends_on:
      - song-service-db
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5433
      DB_NAME: songService
      DB_USER: songService
      DB_PASSWORD: songService
    ports:
      - "8080:8080"

  resource-service:
    build: ./ResourceService
    restart: always
    depends_on:
      - resource-service-db
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5434
      DB_NAME: resourceService
      DB_USER: resourceService
      DB_PASSWORD: resourceService
      AWS_S3_BUCKET: resources-eu-north-1
      AWS_S3_ACCESS_KEY: testtesttest
      AWS_S3_SECRET_KEY: testtesttest
      AWS_S3_REGION: eu-north-1
    ports:
      - "8081:8080"

  song-service-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: songService
      POSTGRES_USER: songService
      POSTGRES_PASSWORD: songService
    ports:
      - "5433:5432"

  resource-service-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: resourceService
      POSTGRES_USER: resourceService
      POSTGRES_PASSWORD: resourceService
    ports:
      - "5434:5432"