spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://${SONG_SERVICE_DB_HOST}:${SONG_SERVICE_DB_PORT}/${SONG_SERVICE_DB_NAME}
    username: ${SONG_SERVICE_DB_USER}
    password: ${SONG_SERVICE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver