spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5433/songService
    username: songService
    password: songService
    driver-class-name: org.postgresql.Driver
server:
  port: 8082